"""
Django settings for socialnetworkapi project.

Generated by 'django-admin startproject' using Django 5.1.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/
import os
from pathlib import Path
import dj_database_url
import pymysql
import cloudinary
import ssl
import certifi

# setup cloudinary
cloudinary.config(
    cloud_name="dbmwgavqz",
    api_key="747824214758252",
    api_secret="IjgCUhqhoxQhoiG1dcq-vWJk5wA",
    secure=True
)

# pymsql setting
pymysql.install_as_MySQLdb()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# change auth user default
AUTH_USER_MODEL = 'socialnetworking.User'

# SECURITY WARNING: keep the secret key used in production secret!
# SECRET_KEY = 'django-insecure-!e8g^ff2j3g(2kgbjic)tk!iwzs4uu%4m!4(^)otr_yg)06vhx'
SECRET_KEY = os.environ.get('SECRET_KEY', 'django-insecure-!e8g^ff2j3g(2kgbjic)tk!iwzs4uu%4m!4(^)otr_yg)06vhx')

# SECURITY WARNING: don't run with debug turned on in production!
# DEBUG = True
DEBUG = os.environ.get('DEBUG', 'False') == 'True'

# media root
# MEDIA_ROOT = '%s/socialnetworking/static/' % BASE_DIR
#
# STATIC_URL = '/static/'

CKEDITOR_UPLOAD_PATH = "images/ckeditor/"

ALLOWED_HOSTS = [
    '159.65.7.106',
    'localhost',
    '*',
]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'socialnetworkapi.socialnetworking.apps.SocialnetworkingConfig',
    'ckeditor',
    'ckeditor_uploader',
    'rest_framework',
    'drf_yasg',
    'debug_toolbar',
    'oauth2_provider',
    'channels'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'debug_toolbar.middleware.DebugToolbarMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'socialnetworkapi.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

# WSGI_APPLICATION = 'socialnetworkapi.wsgi.application'
ASGI_APPLICATION = "socialnetworkapi.asgi.application"

# localhost
# CHANNEL_LAYERS = {
#     "default": {
#         "BACKEND": "channels.layers.InMemoryChannelLayer",
#     },
# }

# cho docker
CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {
            "hosts": [(os.environ.get('REDIS_URL', 'redis://redis:6379'))],
        },
    },
}

# cho railway
# CHANNEL_LAYERS = {
#     "default": {
#         "BACKEND": "channels_redis.core.RedisChannelLayer",
#         "CONFIG": {
#             "hosts": [(os.environ.get('REDIS_URL', 'redis://default:hPWjtughNFOsCWnyWpTbsMyVBBOnGFXo@redis.railway.internal:6379'))],
#         },
#     },
# }

# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

# JAWSDB_URL = os.environ.get('JAWSDB_URL')
# DATABASE_URL = os.environ.get('DATABASE_URL')
#
# if JAWSDB_URL:
#     # Phân tích JAWSDB_URL để lấy thông tin kết nối db
#     DATABASES = {
#         'default': dj_database_url.parse(JAWSDB_URL)
#     }
# elif DATABASE_URL:
#     DATABASES = {
#         'default': dj_database_url.parse(DATABASE_URL, conn_max_age=600)
#     }
# else:
#     # Cấu hình db cho local
#     DATABASES = {
#         'default': {
#             'ENGINE': 'django.db.backends.mysql',
#             'NAME': 'socialnetworkdb',
#             'USER': 'root',
#             'PASSWORD': 'Admin@123',
#             'HOST': 'localhost',
#             'PORT': '3306',
#         }
#     }

# Database (dùng container MySQL)
JAWSDB_URL = os.environ.get('JAWSDB_URL')
DATABASE_URL = os.environ.get('DATABASE_URL')

if JAWSDB_URL:
    DATABASES = {'default': dj_database_url.parse(JAWSDB_URL)}
elif DATABASE_URL:
    DATABASES = {'default': dj_database_url.parse(DATABASE_URL, conn_max_age=600)}
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.mysql',
            'NAME': 'socialnetworkdb',
            'USER': 'root',
            'PASSWORD': os.environ.get('MYSQL_ROOT_PASSWORD', 'Admin@123'),
            'HOST': 'mysql',
            'PORT': '3306',
        }
    }

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'  # Thư mục để collect static files
STATICFILES_DIRS = [BASE_DIR / 'socialnetworkapi/socialnetworking/static']

# Media files configuration (nếu cần)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'oauth2_provider.contrib.rest_framework.OAuth2Authentication',
    )
}

# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

# TIME_ZONE = 'UTC'
TIME_ZONE = 'Asia/Ho_Chi_Minh'

USE_I18N = True
USE_TZ = False

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

INTERNAL_IPS = [
    '127.0.0.1',
]

OAUTH2_PROVIDER = {
    'OAUTH2_BACKEND_CLASS': 'oauth2_provider.oauth2_backends.JSONOAuthLibCore'
}

# Mail setting
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'aluminsocialnetwork@gmail.com'
EMAIL_HOST_PASSWORD = 'sopg qfme htmp zanp'
EMAIL_SSL_CONTEXT = ssl.create_default_context(cafile=certifi.where())

DATA_UPLOAD_MAX_MEMORY_SIZE = 104857600  # 100MB


CSRF_TRUSTED_ORIGINS = [
    'https://web-production-b2ae.up.railway.app',
    'wss://web-production-b2ae.up.railway.app',
    'https://127.0.0.1:8000',
    'ws://127.0.0.1:8000',
    'http://159.65.7.106:8000',
    'ws://159.65.7.106:8000',
]