# Generated by Django 5.1.4 on 2025-01-16 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialnetworking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password_change_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
