# Generated by Django 5.1.4 on 2025-02-15 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialnetworking', '0002_alter_surveyresponse_survey'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='introduce',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
