# Generated by Django 5.1.4 on 2025-02-26 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialnetworking', '0003_alter_user_introduce'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='introduce',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
