# Generated by Django 5.1.4 on 2026-01-25 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialnetworking', '0004_alter_user_introduce'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_verify',
            field=models.BooleanField(default=True),
        ),
    ]
